### ISSUE TITLE
PWM Support

### ISSUE THREAD

**Issue by mghaff007** [garymueller/ESP-131GPIO#3]
Tested your code on 8 relays! Works great thanks! As far as PWM goes how does one implement it? I have a 2 channel PWM dimmer module and was looking for a starting point for testing.

Thanks in advance.

**Comment by garymueller** [comment]
I'm glad your finding it useful and its working out for you.

For simple development testing I use an app [here](https://varaderolights.com/android-app/).  I orginally found it on one of the [christmaslightforums ](http://doityourselfchristmas.com/forums/showthread.php?21482-Android-APP-for-testing-E1-31-devices) and found it useful.  I'm sure there are others out there as well.

The difference between using pwm from my software point of view is that it uses an analogwrite instead of a digitalwrite (Line 82-87).  At one point I thought about using a slider for the test tab instead of a toggle to better support pwm testing but thought people might get confused by that.  If you think it would be useful maybe I could add it later.  

Let me know if the above recomendations help.
