### ISSUE TITLE
upgrade esp8266 library to current version (3.02)

### ISSUE THREAD

**Issue by garymueller** [garymueller/ESP-131GPIO#6]
There are currently runtime issues with the firmware when runing with the latest esp8266 library (3.02).  Issues include #4 and #5.  Issues include firmware not loading or connecting to wifi.  We should update the firmware to be able to support the latest esp8266 library.

Hint: The previous stack trace indicates issues when initializing SPIFFS.  We should update the file system to littlefs and see if that fixes the issue.  See https://arduino-esp8266.readthedocs.io/en/latest/filesystem.html

**Comment by Tom-Neverwinter** [comment]
I will take the boxes inside tomorrow and do some more investigation. 

step one seems to flash using an older version of the "esp8266 library", based on your comment Arduino 8266 (2.74)](https://github.com/esp8266/Arduino/tree/2.7.4**** is a working version.  


"Changes since 2.7.0 (to 2.7.1)
Hotfixes
Revert XMC changes in eboot that were causing OTA failure (#7277)
Revert MDNS listen the current iface causing MDNS death (#7266)
Core (FS)
Deprecate SPIFFS, move examples to LittleFS (#7263)"
